- .gitignore
> [환경] gitignore2차수정

- backend/chatbot/urls.py
- backend/chatbot/views.py
- backend/config/settings.py
- frontend/src/pages/MyPage/MyPage.jsx
- frontend/src/services/authService.js
[수정]FFU-xx 새채팅생성 시 오류사항 수정
* 2025/08/21
새 채팅 생성시 생성이 안되는 문제 해결.
settings.py 일부 설정 사항 변경 
- load_dotenv(BASE_DIR.parent / '.env') 주석 해제함. Mac에서는 주석처리했지만, window환경에서는 주석 시 오류가 발생하여 주석해제 후 push함.
> [수정]FFU-xx 새채팅생성 시 오류사항 수정

- backend/requirements.txt
[환경]PyPDF2설치 추가
* 2025/08/21
PyPDF2 환경 설치 추가
> [환경]PyPDF2설치 추가

- backend/chatbot/urls.py
- backend/chatbot/views.py
- frontend/src/pages/Chat/ChatPage.jsx
- frontend/src/pages/Chat/Sidebar.jsx
[수정]FFU-xx 대화기록 삭제 백엔드 API 추가
* 2025/08/21
대화기록 삭제 백엔드 추가.
> [수정]FFU-xx 대화기록 삭제 백엔드 API 추가

- frontend/src/services/authService.js
[수정]FFC-03 authService.js 중복코드 제거
* 2025/08/21
authService.js 중복코드 제거
// 관리자 여부 확인
isAdmin() {
try {
const user = this.getCurrentUser();
return user && user.auth === 'Y';
} catch (error) {
console.error('관리자 여부 확인 오류:', error);
return false;
}
},
// JWT 토큰 가져오기
getToken() {
return localStorage.getItem('access_token');
},
> [수정]FFC-03 authService.js 중복코드 제거

- backend/chatbot/views.py
- frontend/src/components/LoadingMask.jsx
- frontend/src/pages/Chat/ChatPage.jsx
- frontend/src/pages/Chat/Sidebar.jsx
[수정]채팅기록 삭제시 LoadingMash 추가, 대화기록 제목 update 추가
* 2025/08/21
* 
채팅기록 삭제시 LoadingMash 추가, 대화기록 제목 update 추가
> [수정]채팅기록 삭제시 LoadingMash 추가, 대화기록 제목 update 추가

- .gitignore
- backend/chatbot/services/answerer.py
- backend/chatbot/services/api.py
- backend/chatbot/services/constants.py
- backend/chatbot/services/filters.py
- backend/chatbot/services/keyword_extractor.py
- backend/chatbot/services/pipeline.py
- backend/chatbot/services/rag_search.py
- backend/chatbot/services/rag_service.py
- backend/chatbot/urls.py
- backend/chatbot/views.py
- backend/receipt/utils.py
- backend/requirements.txt
- backend/test_enhanced_rag.py
- frontend/src/pages/Chat/ChatPage.jsx
- frontend/src/services/api.js
[추가]FAC-01 업무가이드용 RAG시스템 고도화
* 2025/08/25
업무가이드용 RAG시스템 고도화
> [추가]FAC-01 업무가이드용 RAG시스템 고도화

- .gitignore
> [환경]gitignore 수정

- backend/authapp/decorators.py
- backend/receipt/urls.py
- backend/receipt/utils.py
- backend/receipt/views.py
- frontend/src/pages/Admin/ManageReceipts.jsx
- frontend/src/pages/Admin/components/DataTable.jsx
feature: 영수증 미리보기 구현
[FFC-12] 영수증 이미지 출력 | 영수증 이미지링크를 클릭 시 preview로 이미지를 띄워준다.
* 2025/08/27
- S3에 있는 이미지를 url을 통해 미리보기 출력
> feature: 영수증 미리보기 구현

- backend/receipt/views.py
[수정]FFU-11 영수증 업로드 오류 수정
* 2025/08/28
영수증 업로드 오류 수정
> [수정]FFU-11 영수증 업로드 오류 수정

- backend/receipt/views.py
- frontend/src/pages/Chat/ChatPage.jsx
- frontend/src/pages/Chat/Receipt.jsx
2025 09 05 금요일
1. 사이드바 상의 영수증 리스트에서 pending 상태의 영수증을 수정하고 최종 저장하여 status가 processed로 바뀔 수 있도록 했습니다.
+ ReceiptListView에서 file_id도 response로 넘겨주도록 했습니다.
> [Feat] pending 상태 영수증 수정 이후 저장 기능 추가

- backend/chatbot/views.py
- frontend/src/pages/Chat/ChatPage.jsx
- frontend/src/services/api.js
[수정]채팅방오류 수정
[수정]console 제거
* 2025/09/07
최종 제거된 console.log/print문 목록
프론트엔드 (95개 제거)
1. frontend/src/services/api.js - 11개 제거
2. frontend/src/pages/Chat/ChatPage.jsx - 45개 제거
3. frontend/src/pages/Admin/MembersPage.jsx - 12개 제거
4. frontend/src/pages/Admin/components/AdminSidebar.jsx - 2개 제거
5. frontend/src/pages/Chat/Sidebar.jsx - 1개 제거
6. frontend/src/pages/Chat/Receipt.jsx - 2개 제거
7. frontend/src/pages/Admin/ChatReportsPage.jsx - 2개 제거
8. frontend/src/pages/Admin/ManageReceipts.jsx - 20개 제거
백엔드 (75개 제거)
1. backend/chatbot/views.py - 58개 제거
2. backend/adminapp/views.py - 52개 제거
유지된 로그
* 에러 로그: console.error() - 디버깅에 필요
* 테스트 파일: test_*.py 파일들의 print문 - 테스트용이므로 유지
총 170개의 불필요한 디버깅 로그가 제거.
> [수정]채팅방오류 수정 및 console제거

- backend/chatbot/services/answerer.py
- backend/chatbot/services/pipeline.py
- backend/chatbot/urls.py
- backend/chatbot/views.py
[수정]업무 가이드 싱글턴 -> 멀티턴 고도화
* 2025/09/09
업무 가이드 싱글턴 -> 멀티턴 고도화
> [수정]업무 가이드 싱글턴 -> 멀티턴 고도화

- backend/config/settings.py
- frontend/src/services/api.js
[수정]운영 주소로 수정
* 2025/09/10
운영 주소로 수정
> [수정]운영 주소로 수정

- backend/config/settings.py
- backend/config/urls.py
- frontend/src/services/api.js
[수정]운영배포 코드로 수정
* 2025/09/14
운영배포 코드로 수정
> [수정]운영배포 코드로 수정

- docker-compose.yml
- nginx/default.conf
[수정]SSL 설정 추가
* 2025/09/14
SSL 설정 추가
> [수정]SSL 설정 추가

- backend/Dockerfile
[수정]도커 최적화
* 2025/09/14
도커 최적화
> [수정]도커 최적화

- nginx/default.conf
[수정]nginx 인증서 오류 수정
* 2025/09/14
nginx 인증서 오류 수정
> [수정]nginx 인증서 오류 수정

- nginx/default.conf
[수정]nginx 최종본
* 2025/09/14
nginx 최종본
> [수정]nginx 최종본

- nginx/default.conf
[수정]CORS중복방지 추가
* 2025/09/14
CORS중복방지 추가
> [수정]CORS중복방지 추가

- nginx/default.conf
[수정]설정파일백엔드포트수정
* 2025/09/14
설정파일백엔드포트수정
> [수정]설정파일백엔드포트수정

- backend/chatbot/services/pipeline.py
[수정]파이프라인 수정
* YYYY/MM/DD
파이프라인 수정
> [수정]파이프라인 수정

- backend/chatbot/views.py
[수정]정보추출 부분 수정
* 2025/09/15
정보추출 부분 수정
> [수정]정보추출 부분 수정
